### ISSUE TITLE
Returning data from the second endpoint

### ISSUE THREAD

**Issue by RRozi** [flokapi/flet-fastapi-example#1]
My first end point performs
@api.register
@app.get("/data")
async def get_html():
    with open("index_data.html", "r") as file:
        html_content = file.read()
    return HTMLResponse(content=html_content, status_code=200)
   
@app.post("/get_data")
async def send_name(request: Request):

    print(2222222222222222222222)
    data = await request.json()
    print(data)
    return data
    
And js in html already returns data but to a different endpoint by 

        fetch('/process_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
.....

How can I get this data in Flet?

**Comment by RRozi** [comment]
I'm working with telegram api web-app

**Comment by RRozi** [comment]
I made a mistake in the ways, they are different

**Comment by RRozi** [comment]
I have updated the code above

**Comment by RRozi** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>
</html>`

**Comment by RRozi** [comment]
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>
</html>
`

**Comment by RRozi** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>
</html>

**Comment by RRozi** [comment]
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>

**Comment by RRozi** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>
</html>

**Comment by RRozi** [comment]
> <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>
</html>

**Comment by RRozi** [comment]
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script>
        let tg = window.Telegram.WebApp;

        let user_id = tg.initDataUnsafe.user.username;
        let colorScheme = tg.colorScheme;

        // Отправка name и colorScheme на сервер FastAPI
        fetch('/get_data', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                user_id: user_id,
                colorScheme: colorScheme
            })
        })
        .then(response => response.json())
        .then(data => {
            console.log('Success:', data);
        })
        .catch((error) => {
            console.error('Error:', error);
        });

        // Вызов метода close()

    </script>
</body>

**Comment by flokapi** [comment]
The issue is not related to this repository.
